Revised the toggleActive function
chihacknight/il-solar-map pull request #64
Opened 2024-07-18 21:21 UTC by viennguyen2026

## Overview

Revised the toggleActive function to address Derek's comment on PR #62 

Closes #62

## Notes

I've tested this and it works on my machine

2024-07-23 21:31 UTC, derekeder requested changes
@viennguyen2026 this is looking good! works as expected when toggling the different buttons. one case to address though

2024-07-23 21:31 UTC, derekeder commented on js/map.js
> +  // calls the toggleActive function on the initial states
we still need to handle the case when the map is loaded with different values set. each time a button is clicked it updates the URL with query parameters. we need to update the code here to account for selecting the right button

2024-08-01 16:48 UTC, viennguyen2026 commented
@derekeder pushed based on the changes discussed above

2024-09-08 19:27 UTC, derekeder approved these changes
sorry this sat for so long @viennguyen2026 - looks good!

2024-09-08 19:27 UTC, merged