Get all data into one place
chihacknight/il-solar-map pull request #7
Opened 2023-05-24 03:10 UTC by SuragNuthulapaty

Combined data from 
`report-3-census-tract-rev.csv`
`ilsfa-2023-05-07.csv`
`solar-eia-plants_1677797680150.geojson`
all into one dictionary, and then aggregated data based upon that

2023-05-24 21:30 UTC, derekeder requested changes
looks good - just a few smaller changes to make and we can bring this in

2023-05-24 21:30 UTC, derekeder commented on data/v2/test.py
> +import requests
we don't need to commit this file

2023-05-24 21:30 UTC, derekeder commented on data/v2/aggregate-data-by-county.py
> +import requests_cache
lets add requests and requests-cache to requirements.txt

2023-05-25 18:59 UTC, SuragNuthulapaty commented
@derekeder I changed the requested changes and updated the readme

2023-05-25 19:05 UTC, derekeder approved these changes
thanks - looks good!

2023-05-25 19:05 UTC, merged